import { DEFAULT_DATE } from "@/lib/constants";
import type { MarketSnapshot, SourceRecord } from "@/lib/types";
import { makeId } from "@/lib/utils";

const rOneSource = (slug: string, notes: string): SourceRecord => ({
  id: makeId("source"),
  slug,
  title: "한국부동산원 R-ONE 시장지표",
  publisher: "한국부동산원",
  url: "https://www.reb.or.kr/r-one/",
  retrievedAt: DEFAULT_DATE,
  publishedAt: "2026-02-28",
  notes,
});

export const promotedMarketSnapshots: MarketSnapshot[] = [
  {
    id: "market_seoul_core",
    slug: "seoul-core",
    regionName: "서울 핵심 생활권",
    lifestyleLabel: "마포·성동·광진·영등포",
    publishedMonth: "2026-02",
    reviewStatus: "promoted",
    freshness: "fresh",
    priceBandLow: 950_000_000,
    priceBandMid: 1_180_000_000,
    priceBandHigh: 1_420_000_000,
    momChangePct: 0.4,
    yoyChangePct: 2.1,
    commuteLabel: "서울 업무지구 접근 우수",
    notes: "중형 구축 및 준신축 실거주 밴드 중심",
    sourceRecords: [rOneSource("r-one-seoul-core", "서울 아파트 매매가격지수와 실거래 흐름을 반영한 검수 완료 밴드")],
  },
  {
    id: "market_seoul_outer",
    slug: "seoul-outer",
    regionName: "서울 외곽 실거주권",
    lifestyleLabel: "은평·노원·강서·구로",
    publishedMonth: "2026-02",
    reviewStatus: "promoted",
    freshness: "fresh",
    priceBandLow: 720_000_000,
    priceBandMid: 860_000_000,
    priceBandHigh: 1_020_000_000,
    momChangePct: 0.3,
    yoyChangePct: 1.7,
    commuteLabel: "서울 내 통근 가능, 예산 방어력 양호",
    notes: "59~74㎡ 실거주형 아파트 기준",
    sourceRecords: [rOneSource("r-one-seoul-outer", "서울 외곽권 가격지수와 거래 회복세 반영")],
  },
  {
    id: "market_gwangmyeong_anyang",
    slug: "gwangmyeong-anyang",
    regionName: "광명·안양",
    lifestyleLabel: "광명 철산·안양 평촌권",
    publishedMonth: "2026-02",
    reviewStatus: "promoted",
    freshness: "fresh",
    priceBandLow: 680_000_000,
    priceBandMid: 830_000_000,
    priceBandHigh: 980_000_000,
    momChangePct: 0.2,
    yoyChangePct: 1.5,
    commuteLabel: "여의도·강남 양방향 접근 균형",
    notes: "정비사업 기대와 교통 프리미엄 반영",
    sourceRecords: [rOneSource("r-one-gwangmyeong-anyang", "서남권 인접 경기지역 비교용 밴드")],
  },
  {
    id: "market_bundang_pangyo",
    slug: "bundang-pangyo",
    regionName: "분당·판교 인접권",
    lifestyleLabel: "분당·판교·정자",
    publishedMonth: "2026-02",
    reviewStatus: "promoted",
    freshness: "fresh",
    priceBandLow: 900_000_000,
    priceBandMid: 1_150_000_000,
    priceBandHigh: 1_420_000_000,
    momChangePct: 0.5,
    yoyChangePct: 2.8,
    commuteLabel: "테크 직장 접근성 우수",
    notes: "분당 생활권 선호가 강한 가구용",
    sourceRecords: [rOneSource("r-one-bundang-pangyo", "성남 분당권 시세와 거래 회복 반영")],
  },
  {
    id: "market_hanam_guri",
    slug: "hanam-guri",
    regionName: "하남·구리",
    lifestyleLabel: "미사·덕풍·갈매권",
    publishedMonth: "2026-02",
    reviewStatus: "promoted",
    freshness: "fresh",
    priceBandLow: 650_000_000,
    priceBandMid: 790_000_000,
    priceBandHigh: 930_000_000,
    momChangePct: 0.2,
    yoyChangePct: 1.3,
    commuteLabel: "강동·잠실 접근성 우수",
    notes: "신축 선호와 교통개선 기대 반영",
    sourceRecords: [rOneSource("r-one-hanam-guri", "동부권 인접 경기지역 밴드")],
  },
  {
    id: "market_goyang_bucheon",
    slug: "goyang-bucheon",
    regionName: "고양·부천",
    lifestyleLabel: "일산·덕양·상동권",
    publishedMonth: "2026-02",
    reviewStatus: "promoted",
    freshness: "pending",
    priceBandLow: 540_000_000,
    priceBandMid: 690_000_000,
    priceBandHigh: 820_000_000,
    momChangePct: 0.1,
    yoyChangePct: 0.9,
    commuteLabel: "서울 서북권·여의도 접근형",
    notes: "신규 발표 대기 상태를 가정한 최근 검수 기준 밴드",
    sourceRecords: [rOneSource("r-one-goyang-bucheon", "최근 공식 발표값 유지, 최신 발표 대기 중")],
  },
];
