import type { InterviewQuestion } from "@/lib/types";

export const interviewQuestions: InterviewQuestion[] = [
  {
    id: "hyunminMonthlyNetIncome",
    speaker: "재무 플래너",
    prompt: "현민의 월 실수령은 얼마인가요?",
    placeholder: "예: 450만원",
    kind: "money",
  },
  {
    id: "hyunminMonthlyVariableIncome",
    speaker: "재무 플래너",
    prompt: "현민의 월 변동수입 평균은 얼마인가요?",
    placeholder: "예: 40만원, 없으면 0",
    kind: "money",
  },
  {
    id: "nuriMonthlyNetIncome",
    speaker: "재무 플래너",
    prompt: "누리의 월 실수령은 얼마인가요?",
    placeholder: "예: 320만원",
    kind: "money",
  },
  {
    id: "nuriMonthlyVariableIncome",
    speaker: "재무 플래너",
    prompt: "누리의 월 변동수입 평균은 얼마인가요?",
    placeholder: "예: 30만원, 없으면 0",
    kind: "money",
  },
  {
    id: "monthlyFixedExpenses",
    speaker: "재무 플래너",
    prompt: "주거비를 제외한 월 고정지출은 얼마인가요?",
    placeholder: "예: 280만원",
    kind: "money",
  },
  {
    id: "monthlyCurrentHousingCost",
    speaker: "재무 플래너",
    prompt: "현재 주거비는 월 얼마인가요?",
    placeholder: "예: 90만원",
    kind: "money",
  },
  {
    id: "currentMonthlySavings",
    speaker: "재무 플래너",
    prompt: "현재 월 평균 저축 가능액은 얼마인가요?",
    placeholder: "예: 230만원",
    kind: "money",
  },
  {
    id: "cashAssets",
    speaker: "재무 플래너",
    prompt: "예금·적금·현금성 자산 합계는 얼마인가요?",
    placeholder: "예: 1.8억",
    kind: "money",
  },
  {
    id: "subscriptionSavings",
    speaker: "재무 플래너",
    prompt: "청약·주택저축 잔액은 얼마인가요?",
    placeholder: "예: 1800만원",
    kind: "money",
  },
  {
    id: "jeonseReturnAmount",
    speaker: "재무 플래너",
    prompt: "돌려받을 수 있는 전세보증금은 얼마인가요?",
    placeholder: "예: 7000만원, 없으면 0",
    kind: "money",
  },
  {
    id: "outstandingDebt",
    speaker: "재무 플래너",
    prompt: "남아있는 대출 원금 합계는 얼마인가요?",
    placeholder: "예: 2500만원, 없으면 0",
    kind: "money",
  },
  {
    id: "otherDebtMonthlyService",
    speaker: "재무 플래너",
    prompt: "다른 대출의 월 상환액은 얼마인가요?",
    placeholder: "예: 35만원, 없으면 0",
    kind: "money",
  },
  {
    id: "expectedAnnualBonus",
    speaker: "재무 플래너",
    prompt: "연 보너스나 비정기 수입 합계는 얼마인가요?",
    placeholder: "예: 1200만원, 없으면 0",
    kind: "money",
  },
  {
    id: "preferredRegions",
    speaker: "재무 플래너",
    prompt: "희망 생활권을 적어주세요.",
    placeholder: "예: 마포, 광명, 성남 분당",
    kind: "text",
  },
  {
    id: "commuteMaxMinutes",
    speaker: "재무 플래너",
    prompt: "각자 수용 가능한 최대 편도 통근시간은 몇 분인가요?",
    placeholder: "예: 60",
    kind: "number",
  },
  {
    id: "targetTimeframeMonths",
    speaker: "재무 플래너",
    prompt: "매수 목표 시점은 몇 개월 후인가요?",
    placeholder: "예: 48",
    kind: "number",
  },
];
